name: Bug report for Comboser
description: Make a bug report and help to improve Comboser
title: "[Bug]: "
labels: [bug]
assignees:
- im-coder-lg

body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this feature request!

- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: "A detailed and clear concise description of the bug:"
    placeholder: "Bug description:"
    value: "What happened in the bug:"
  validations:
    required: true
- type: textarea
  id: expectations
  attributes:
    label: What did you expect to happen?
    description: "A detailed and concise description of what you expected to happen:"
    placeholder: "What you expected to happen:"
    value: "Eg: Expected to see this..."
    
- type: textarea
  id: version-of-os
  attributes:
    label: Version of OS
    description: "What version of the OS are you running?"
    placeholder: "OS Version"
    value: "Eg: Windows 21H1 Build 19043.2 or macOS Big Sur 11.2 or Ubuntu 20.04.2 Focal Fossa"
  validations:
    required: true
